version: '3.7'

services:
  java:
    build:
      context: ./
      dockerfile: ./operations/docker/java/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/opt/app
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=fraud_detection
      - MYSQL_USER=edcast
      - MYSQL_PASSWORD=pass
    ports:
      - "3396:3306"
    restart: always
